#!/bin/bash
cd ~/sviluppo/app/phonegap/bodio/bodio/src/

lessc less/index.less > ../www/css/index.css
cat 'js/customization.js' > ../www/js/app.js
cat 'node_modules/jquery/dist/jquery.js'  >> ../www/js/app.js
cat 'node_modules/angular/angular.js'  >> ../www/js/app.js
cat 'node_modules/angular-ui-router/release/angular-ui-router.js'  >> ../www/js/app.js
cat 'node_modules/angular-resource/angular-resource.js'  >> ../www/js/app.js
cat 'node_modules/angular-i18n/angular-locale_it-it.js'  >> ../www/js/app.js
cat 'node_modules/angular-touch/angular-touch.js'  >> ../www/js/app.js
cat 'node_modules/angular-sanitize/angular-sanitize.js'  >> ../www/js/app.js
cat 'node_modules/ngStorage/ngStorage.js'  >> ../www/js/app.js           
cat 'node_modules/iscroll/build/iscroll-zoom.js'  >> ../www/js/app.js
cat 'node_modules/semantic-ui/dist/semantic.min.js'  >> ../www/js/app.js
cat 'node_modules/photoswipe/dist/photoswipe.js'  >> ../www/js/app.js
cat 'node_modules/photoswipe/dist/photoswipe-ui-default.js'  >> ../www/js/app.js
cat 'node_modules/qrcodejs/qrcode.js'  >> ../www/js/app.js
cat 'js/dbaccess.js' >> ../www/js/app.js
cat 'js/when_ready.js' >> ../www/js/app.js
cat 'js/initialize_app.js' >> ../www/js/app.js
cat 'js/controllers.js' >> ../www/js/app.js
find "js/controllers/" -name '*.js' -exec cat {} >> "../www/js/app.js" \;
cat "libs/emergenza/js/emergenza.js" >> "../www/js/app.js"
cat "libs/utilities/js/jquery.linkify.js" >> "../www/js/app.js"
cat "libs/utilities/js/utilities.js" >> "../www/js/app.js"
cat "js/index.js" >> "../www/js/app.js"

cd -

